name: Run test case

on:
    push:
    pull_request:
    release:
        types:
            - published
            - prereleased

jobs:

    run_test_case:

        runs-on: ubuntu-latest
        strategy:
          matrix:
            otp: [23.2]
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: gleam-lang/setup-erlang@v1.1.2
          with:
            otp-version: ${{ matrix.otp }}
        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v1.8
          with:
            cmake-version: '3.16.9'
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover
        - uses: actions/upload-artifact@v1
          if: always()
          with:
            name: logs
            path: _build/test/logs
        - uses: actions/upload-artifact@v1
          with:
            name: cover
            path: _build/test/cover
